language: objective-c
osx_image: xcode12

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SwiftyNotifications.xcworkspace
  - FRAMEWORK_SCHEME="SwiftyNotifications"
  - SDK=iphonesimulator14.0
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=14.0,name=iPhone 11 Pro"
    - DESTINATION="OS=13.5,name=iPhone 11"
    - DESTINATION="OS=12.1,name=iPhone X"
    - DESTINATION="OS=11.4,name=iPhone 8"

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/SwiftyNotifications-*/
- rvm use $RVM_RUBY_VERSION

install:
- gem install bundler
- bundle install

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES build | xcpretty;
    fi

after_success: slather
